import { create } from 'zustand'

const translations = {
  en: {
    // Navbar
    home: "Home",
    weather: "Weather",
    aiChat: "AI Chat",
    crops: "Crops",
    advice: "Advice",
    dashboard: "Dashboard",
    login: "Login",
    logout: "Logout",
    getStarted: "Get Started",
    
    // Home
    builtForFarmers: "🌾 Built for Indian Farmers",
    smartFarmingStartsHere: "Smart Farming",
    startsHere: "Starts Here",
    heroDesc: "KrishiMitra gives every farmer access to expert advice, live weather, and crop guidance — right from your phone. No experience needed.",
    startForFree: "Start for Free →",
    tryAIChat: "Try AI Chat",
    farmersHelped: "Farmers Helped",
    cropTypes: "Crop Types",
    aiAvailable: "AI Available",
    toUse: "To Use",
    everythingFarmerNeeds: "Everything a Farmer Needs",
    onePlatform: "One platform for all your farming questions and decisions.",
    aiFarmingAssistant: "AI Farming Assistant",
    aiFarmingDesc: "Ask anything about your crops, soil, or farming practices in your language.",
    liveWeather: "Live Weather Info",
    liveWeatherDesc: "Get real-time weather updates and forecasts for your exact location.",
    cropRecommendations: "Crop Recommendations",
    cropRecommendationsDesc: "Know which crops to grow based on your soil type and season.",
    farmingAdvice: "Farming Advice",
    farmingAdviceDesc: "Get expert tips on irrigation, fertilizers, and best practices.",
    trustedReliable: "Trusted & Reliable",
    trustedReliableDesc: "Built specifically for Indian farmers with local knowledge.",
    voiceSupport: "Voice Support (Soon)",
    voiceSupportDesc: "Talk to the AI assistant in Hindi or your regional language.",
    readyToFarm: "Ready to farm smarter?",
    joinThousands: "Join thousands of farmers already using KrishiMitra.",
    createFreeAccount: "Create Free Account →",
    builtWithLove: "Built with ❤️ for Indian Farmers",
    
    // Login
    welcomeBack: "Welcome Back",
    loginToAccount: "Login to your KrishiMitra account",
    phoneNumber: "Phone Number",
    phonePlaceholder: "Your registered phone number",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    loginButton: "Login to KrishiMitra",
    loggingIn: "Logging in...",
    or: "or",
    tryDemo: "🌾 Try Demo Account",
    newToKrishiMitra: "New to KrishiMitra?",
    createFreeAccountLink: "Create free account",
    
    // Register
    createAccount: "Create Account",
    joinKrishiMitra: "Join KrishiMitra — it's free forever",
    fullName: "Full Name",
    fullNamePlaceholder: "Enter your full name",
    phonePlaceholderReg: "10-digit mobile number",
    state: "State",
    select: "Select",
    district: "District",
    districtPlaceholder: "Your district",
    createStrongPassword: "Create a strong password",
    createAccountButton: "Create My Account",
    creatingAccount: "Creating Account...",
    alreadyHaveAccount: "Already have an account?",
    loginHere: "Login here",
    
    // Chat
    aiFarmingAssistantTitle: "AI Farming Assistant",
    askAboutFarming: "Ask anything about farming, crops, or agriculture",
    quickQuestions: "QUICK QUESTIONS",
    askAboutCrops: "Ask about crops, soil, fertilizers...",
    pressEnter: "Press Enter to send · Shift+Enter for new line",
    welcomeMessage: "Namaste! 🙏 I am KrishiMitra, your smart farming assistant. Ask me anything about crops, soil, weather, fertilizers, or farming techniques. I am here to help!",
    
    // Suggestions
    whichCropsJune: "Which crops should I grow in June?",
    increaseWheatYield: "How to increase wheat yield?",
    fertilizerRice: "Best fertilizer for rice crops?",
    protectPests: "How to protect crops from pests?",
    whenIrrigate: "When should I irrigate my field?",
    soilTomatoes: "What is the best soil for tomatoes?",

    // Crops Page
    cropGuide: "Crop Guide",
    cropGuideDesc: "Season-wise info, MSP prices & farming tips",
    yourSoil: "Your soil:",
    suitableCrops: "suitable crops highlighted",
    filterByMySoil: "Filter by my soil",
    searchPlaceholder: "Search by crop name, Hindi name, or soil type...",
    season: "SEASON",
    waterNeed: "WATER NEED",
    soilType: "SOIL TYPE",
    showing: "Showing",
    crops: "crops",
    filteredBy: "· filtered by",
    soil: "soil",
    suitableForYour: "✓ Suitable for your",
    soil: "soil",
    temp: "Temp",
    water: "Water",
    duration: "Duration",
    mspPrice: "MSP Price",
    avgYield: "Avg Yield",
    growing: "Growing:",
    hideDetails: "Hide details",
    fullDetails: "Full details",
    bestStates: "Best States",
    commonPests: "Common Pests / Diseases",
    farmingTips: "Farming Tips",
    profitPotential: "Profit Potential",
    noCropsMatch: "No crops match your filters",
    tryClearing: "Try clearing a filter or changing your search",
    clearAllFilters: "Clear all filters",

    // Advice Page
    farmingAdviceTitle: "Farming Advice",
    farmingAdviceDesc: "In-depth expert guidance on soil, irrigation, pests, fertilizers and more",
    searchAdvicePlaceholder: "Search advice topics...",
    allTopics: "All Topics",
    soilCategory: "Soil",
    irrigationCategory: "Irrigation",
    pestControlCategory: "Pest Control",
    fertilizersCategory: "Fertilizers",
    harvestCategory: "Harvest",
    showingArticles: "Showing",
    articles: "articles",
    noArticlesFound: "No articles found",
    tryDifferentSearch: "Try a different search term",
    readTime: "read",
    soilHealth: "Soil Health",
    waterManagement: "Water Management",
    pestManagement: "Pest Management",
    soilImprovement: "Soil Improvement",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
  },
  hi: {
    // Navbar
    home: "होम",
    weather: "मौसम",
    aiChat: "AI चैट",
    crops: "फसलें",
    advice: "सलाह",
    dashboard: "डैशबोर्ड",
    login: "लॉगिन",
    logout: "लॉगआउट",
    getStarted: "शुरू करें",
    
    // Home
    builtForFarmers: "🌾 भारतीय किसानों के लिए बनाया गया",
    smartFarmingStartsHere: "स्मार्ट खेती",
    startsHere: "यहाँ से शुरू करें",
    heroDesc: "कृषिमित्र हर किसान को विशेषज्ञ सलाह, लाइव मौसम, और फसल मार्गदर्शन तक पहुँच देता है — सीधे आपके फोन से। किसी अनुभव की आवश्यकता नहीं।",
    startForFree: "मुफ्त शुरू करें →",
    tryAIChat: "AI चैट आज़माएं",
    farmersHelped: "किसानों की मदद की",
    cropTypes: "फसल प्रकार",
    aiAvailable: "AI उपलब्ध",
    toUse: "उपयोग करने के लिए",
    everythingFarmerNeeds: "जो किसान को चाहिए",
    onePlatform: "अपने सभी खेती सवालों और निर्णयों के लिए एक प्लेटफ़ॉर्म।",
    aiFarmingAssistant: "AI खेती सहायक",
    aiFarmingDesc: "अपनी भाषा में अपनी फसलों, मिट्टी, या खेती प्रथाओं के बारे में कुछ भी पूछें।",
    liveWeather: "लाइव मौसम जानकारी",
    liveWeatherDesc: "अपने सटीक स्थान के लिए रीयल-टाइम मौसम अपडेट और पूर्वानुमान प्राप्त करें।",
    cropRecommendations: "फसल सिफारिशें",
    cropRecommendationsDesc: "अपनी मिट्टी के प्रकार और मौसम के आधार पर कौन सी फसलें उगानी हैं, जानें।",
    farmingAdvice: "खेती सलाह",
    farmingAdviceDesc: "सिंचाई, उर्वरकों और सर्वोत्तम प्रथाओं पर विशेषज्ञ सुझाव प्राप्त करें।",
    trustedReliable: "विश्वसनीय और भरोसेमंद",
    trustedReliableDesc: "स्थानीय ज्ञान के साथ विशेष रूप से भारतीय किसानों के लिए बनाया गया।",
    voiceSupport: "वॉइस सपोर्ट (जल्द आ रहा है)",
    voiceSupportDesc: "हिंदी या अपनी क्षेत्रीय भाषा में AI सहायक से बात करें।",
    readyToFarm: "स्मार्ट खेती के लिए तैयार हैं?",
    joinThousands: "पहले से कृषिमित्र का उपयोग कर रहे हजारों किसानों से जुड़ें।",
    createFreeAccount: "मुफ्त खाता बनाएं →",
    builtWithLove: "भारतीय किसानों के लिए ❤️ से बनाया गया",
    
    // Login
    welcomeBack: "वापसी पर स्वागत है",
    loginToAccount: "अपने कृषिमित्र खाते में लॉगिन करें",
    phoneNumber: "फोन नंबर",
    phonePlaceholder: "आपका पंजीकृत फोन नंबर",
    password: "पासवर्ड",
    passwordPlaceholder: "अपना पासवर्ड दर्ज करें",
    loginButton: "कृषिमित्र में लॉगिन करें",
    loggingIn: "लॉगिन हो रहा है...",
    or: "या",
    tryDemo: "🌾 डेमो खाता आज़माएं",
    newToKrishiMitra: "कृषिमित्र पर नए हैं?",
    createFreeAccountLink: "मुफ्त खाता बनाएं",
    
    // Register
    createAccount: "खाता बनाएं",
    joinKrishiMitra: "कृषिमित्र से जुड़ें — यह हमेशा मुफ्त है",
    fullName: "पूरा नाम",
    fullNamePlaceholder: "अपना पूरा नाम दर्ज करें",
    phonePlaceholderReg: "10 अंकों का मोबाइल नंबर",
    state: "राज्य",
    select: "चुनें",
    district: "जिला",
    districtPlaceholder: "आपका जिला",
    createStrongPassword: "एक मजबूत पासवर्ड बनाएं",
    createAccountButton: "मेरा खाता बनाएं",
    creatingAccount: "खाता बनाया जा रहा है...",
    alreadyHaveAccount: "पहले से खाता है?",
    loginHere: "यहाँ लॉगिन करें",
    
    // Chat
    aiFarmingAssistantTitle: "AI खेती सहायक",
    askAboutFarming: "खेती, फसलों या कृषि के बारे में कुछ भी पूछें",
    quickQuestions: "त्वरित प्रश्न",
    askAboutCrops: "फसलों, मिट्टी, उर्वरकों के बारे में पूछें...",
    pressEnter: "भेजने के लिए Enter दबाएं · नई लाइन के लिए Shift+Enter",
    welcomeMessage: "नमस्ते! 🙏 मैं कृषिमित्र हूं, आपका स्मार्ट खेती सहायक। फसलों, मिट्टी, मौसम, उर्वरकों या खेती तकनीकों के बारे में मुझसे कुछ भी पूछें। मैं यहाँ मदद करने के लिए हूं!",
    
    // Suggestions
    whichCropsJune: "जून में कौन सी फसलें उगानी चाहिए?",
    increaseWheatYield: "गेहूं की पैदावार कैसे बढ़ाएं?",
    increaseWheatYield: "गेहूं की पैदावार कैसे बढ़ाएं?",
    fertilizerRice: "चावल की फसल के लिए सबसे अच्छा उर्वरक?",
    protectPests: "फसलों की कीटों से सुरक्षा कैसे करें?",
    whenIrrigate: "मुझे अपने खेत की सिंचाई कब करनी चाहिए?",
    soilTomatoes: "टमाटर के लिए सबसे अच्छी मिट्टी क्या है?",

    // Crops Page
    cropGuide: "फसल गाइड",
    cropGuideDesc: "मौसम-वार जानकारी, MSP कीमतें और खेती टिप्स",
    yourSoil: "आपकी मिट्टी:",
    suitableCrops: "उपयुक्त फसलें हाइलाइट की गई",
    filterByMySoil: "मेरी मिट्टी से फ़िल्टर करें",
    searchPlaceholder: "फसल का नाम, हिंदी नाम, या मिट्टी के प्रकार से खोजें...",
    season: "मौसम",
    waterNeed: "पानी की जरूरत",
    soilType: "मिट्टी का प्रकार",
    showing: "दिखा रहा है",
    crops: "फसलें",
    filteredBy: "· फ़िल्टर किया गया",
    soil: "मिट्टी",
    suitableForYour: "✓ आपकी के लिए उपयुक्त",
    soil: "मिट्टी",
    temp: "तापमान",
    water: "पानी",
    duration: "अवधि",
    mspPrice: "MSP कीमत",
    avgYield: "औसत उपज",
    growing: "उगाना:",
    hideDetails: "विवरण छिपाएं",
    fullDetails: "पूरा विवरण",
    bestStates: "सर्वश्रेष्ठ राज्य",
    commonPests: "सामान्य कीट / रोग",
    farmingTips: "खेती टिप्स",
    profitPotential: "लाभ की संभावना",
    noCropsMatch: "कोई फसल आपके फ़िल्टर से मेल नहीं खाती",
    tryClearing: "फ़िल्टर साफ़ करने का प्रयास करें या खोज बदलें",
    clearAllFilters: "सभी फ़िल्टर साफ़ करें",

    // Advice Page
    farmingAdviceTitle: "खेती सलाह",
    farmingAdviceDesc: "मिट्टी, सिंचाई, कीट, उर्वरकों और अधिक पर गहन विशेषज्ञ मार्गदर्शन",
    searchAdvicePlaceholder: "सलाह विषयों की खोज करें...",
    allTopics: "सभी विषय",
    soilCategory: "मिट्टी",
    irrigationCategory: "सिंचाई",
    pestControlCategory: "कीट नियंत्रण",
    fertilizersCategory: "उर्वरक",
    harvestCategory: "फसल कटाई",
    showingArticles: "दिखा रहा है",
    articles: "लेख",
    noArticlesFound: "कोई लेख नहीं मिला",
    tryDifferentSearch: "एक अलग खोज शब्द आज़माएं",
    readTime: "पढ़ने का समय",
    soilHealth: "मिट्टी स्वास्थ्य",
    waterManagement: "पानी प्रबंधन",
    pestManagement: "कीट प्रबंधन",
    soilImprovement: "मिट्टी सुधार",
    beginner: "शुरुआती",
    intermediate: "मध्यम",
    advanced: "उन्नत",
  },
  ta: {
    // Navbar
    home: "முகப்பு",
    weather: "வானிலை",
    aiChat: "AI அரட்டை",
    crops: "பயிர்கள்",
    advice: "ஆலோசனை",
    dashboard: "டாஷ்போர்டு",
    login: "உள்நுழைக",
    logout: "வெளியேறு",
    getStarted: "தொடங்கு",
    
    // Home
    builtForFarmers: "🌾 இந்திய விவசாயிகளுக்காக",
    smartFarmingStartsHere: "ஸ்மார்ட் வேளாண்மை",
    startsHere: "இங்கே தொடங்குங்கள்",
    heroDesc: "கிருஷிமித்ரா ஒவ்வொரு விவசாயிக்கும் நிபுணர் ஆலோசனை, நேரடி வானிலை மற்றும் பயிர் வழிகாட்டுதலை வழங்குகிறது — நேரடியாக உங்கள் தொலைபேசியிலிருந்து. எந்த அனுபவமும் தேவையில்லை.",
    startForFree: "இலவசமாகத் தொடங்கு →",
    tryAIChat: "AI அரட்டை முயற்சிக்கவும்",
    farmersHelped: "விவசாயிகளுக்கு உதவியது",
    cropTypes: "பயிர் வகைகள்",
    aiAvailable: "AI கிடைக்கும்",
    toUse: "பயன்படுத்த",
    everythingFarmerNeeds: "விவசாயிக்குத் தேவையானவை",
    onePlatform: "உங்கள் அனைத்து வேளாண் கேள்விகள் மற்றும் முடிவுகளுக்கு ஒரு தளம்.",
    aiFarmingAssistant: "AI வேளாண் உதவியாளர்",
    aiFarmingDesc: "உங்கள் மொழியில் உங்கள் பயிர்கள், மண் அல்லது வேளாண் நடைமுறைகள் பற்றி எதையும் கேளுங்கள்.",
    liveWeather: "நேரடி வானிலை தகவல்",
    liveWeatherDesc: "உங்கள் சரியான இடத்திற்கான ரியல்-டைம் வானிலை புதுப்பிப்புகள் மற்றும் முன்னறிவிப்புகளைப் பெறுங்கள்.",
    cropRecommendations: "பயிர் பரிந்துரைகள்",
    cropRecommendationsDesc: "உங்கள் மண் வகை மற்றும் பருவத்தின் அடிப்படையில் எந்தப் பயிர்களை வளர்ப்பது என்பதை அறியவும்.",
    farmingAdvice: "வேளாண் ஆலோசனை",
    farmingAdviceDesc: "பாசனம், உரங்கள் மற்றும் சிறந்த நடைமுறைகள் பற்றிய நிபுணர் குறிப்புகளைப் பெறுங்கள்.",
    trustedReliable: "நம்பகமானது",
    trustedReliableDesc: "உள்ளூர் அறிவுடன் குறிப்பாக இந்திய விவசாயிகளுக்காக உருவாக்கப்பட்டது.",
    voiceSupport: "குரல் ஆதரவு (வருகிறது)",
    voiceSupportDesc: "இந்தி அல்லது உங்கள் பிராந்திய மொழியில் AI உதவியாளருடன் பேசுங்கள்.",
    readyToFarm: "ஸ்மார்ட் வேளாண்மைக்கு தயாரா?",
    joinThousands: "ஏற்கனவே கிருஷிமித்ராவைப் பயன்படுத்தும் ஆயிரக்கணக்கான விவசாயிகளுடன் இணையுங்கள்.",
    createFreeAccount: "இலவசக் கணக்கை உருவாக்கு →",
    builtWithLove: "இந்திய விவசாயிகளுக்காக ❤️ உடன் உருவாக்கப்பட்டது",
    
    // Login
    welcomeBack: "மீண்டும் வரவேற்கிறோம்",
    loginToAccount: "உங்கள் கிருஷிமித்ரா கணக்கில் உள்நுழைக",
    phoneNumber: "தொலைபேசி எண்",
    phonePlaceholder: "உங்கள் பதிவுசெய்த தொலைபேசி எண்",
    password: "கடவுச்சொல்",
    passwordPlaceholder: "உங்கள் கடவுச்சொல்லை உள்ளிடவும்",
    loginButton: "கிருஷிமித்ராவில் உள்நுழைக",
    loggingIn: "உள்நுழைகிறது...",
    or: "அல்லது",
    tryDemo: "🌾 டெமோ கணக்கை முயற்சிக்கவும்",
    newToKrishiMitra: "கிருஷிமித்ராவில் புதியவரா?",
    createFreeAccountLink: "இலவசக் கணக்கை உருவாக்கவும்",
    
    // Register
    createAccount: "கணக்கை உருவாக்கு",
    joinKrishiMitra: "கிருஷிமித்ராவில் சேருங்கள் — இது எப்போதும் இலவசம்",
    fullName: "முழு பெயர்",
    fullNamePlaceholder: "உங்கள் முழு பெயரை உள்ளிடவும்",
    phonePlaceholderReg: "10 இலக்க மொபைல் எண்",
    state: "மாநிலம்",
    select: "தேர்வு",
    district: "மாவட்டம்",
    districtPlaceholder: "உங்கள் மாவட்டம்",
    createStrongPassword: "ஒரு வலுவான கடவுச்சொல்லை உருவாக்கவும்",
    createAccountButton: "எனது கணக்கை உருவாக்கு",
    creatingAccount: "கணக்கை உருவாக்குகிறது...",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    loginHere: "இங்கே உள்நுழைக",
    
    // Chat
    aiFarmingAssistantTitle: "AI வேளாண் உதவியாளர்",
    askAboutFarming: "வேளாண்மை, பயிர்கள் அல்லது வேளாண்மை பற்றி எதையும் கேளுங்கள்",
    quickQuestions: "விரைவான கேள்விகள்",
    askAboutCrops: "பயிர்கள், மண், உரங்கள் பற்றி கேளுங்கள்...",
    pressEnter: "அனுப்ப Enter அழுத்தவும் · புதிய வரிக்கு Shift+Enter",
    welcomeMessage: "வணக்கம்! 🙏 நான் கிருஷிமித்ரா, உங்கள் ஸ்மார்ட் வேளாண் உதவியாளர். பயிர்கள், மண், வானிலை, உரங்கள் அல்லது வேளாண் நுட்பங்கள் பற்றி எதையும் என்னிடம் கேளுங்கள். நான் உதவ இங்கே இருக்கிறேன்!",
    
    // Suggestions
    whichCropsJune: "ஜூன் மாதத்தில் எந்தப் பயிர்களை வளர்க்க வேண்டும்?",
    increaseWheatYield: "கோதுமை விளைச்சலை எப்படி அதிகரிக்க?",
    fertilizerRice: "நெல் பயிர்களுக்கு சிறந்த உரம்?",
    protectPests: "பயிர்களை பூச்சிகளிடமிருந்து எப்படி பாதுகாப்பது?",
    whenIrrigate: "எப்போது என் வயலுக்கு நீர் பாய்ச்ச வேண்டும்?",
    soilTomatoes: "தக்காளிக்கு சிறந்த மண் எது?",

    // Crops Page
    cropGuide: "பயிர் வழிகாட்டி",
    cropGuideDesc: "பருவம் வாரி தகவல், MSP விலை & வேளாண் குறிப்புகள்",
    yourSoil: "உங்கள் மண்:",
    suitableCrops: "பொருத்தமான பயிர்கள் சுட்டிக்காட்டப்பட்டன",
    filterByMySoil: "என் மண்ணால் வடிகட்டு",
    searchPlaceholder: "பயிர் பெயர், இந்தி பெயர், அல்லது மண் வகையால் தேடுங்கள்...",
    season: "பருவம்",
    waterNeed: "தண்ணீர் தேவை",
    soilType: "மண் வகை",
    showing: "காட்டுகிறது",
    crops: "பயிர்கள்",
    filteredBy: "· வடிகட்டப்பட்டது",
    soil: "மண்",
    suitableForYour: "✓ உங்களுக்கு பொருத்தமான",
    soil: "மண்",
    temp: "வெப்பநிலை",
    water: "தண்ணீர்",
    duration: "காலம்",
    mspPrice: "MSP விலை",
    avgYield: "சராசரி விளைச்சல்",
    growing: "வளர்கிறது:",
    hideDetails: "விவரங்களை மறை",
    fullDetails: "முழு விவரங்கள்",
    bestStates: "சிறந்த மாநிலங்கள்",
    commonPests: "பொதுவான பூச்சிகள் / நோய்கள்",
    farmingTips: "வேளாண் குறிப்புகள்",
    profitPotential: "இலாப சாத்துக்கள்",
    noCropsMatch: "உங்கள் வடிப்பான்களுடன் பயிர்கள் இல்லை",
    tryClearing: "வடிப்பானை அழிக்க முயற்சிக்கவும் அல்லது தேடலை மாற்றவும்",
    clearAllFilters: "அனைத்து வடிப்பான்களையும் அழி",

    // Advice Page
    farmingAdviceTitle: "வேளாண் ஆலோசனை",
    farmingAdviceDesc: "மண், பாசனம், பூச்சிகள், உரங்கள் மற்றும் பலவற்றில் ஆழமான நிபுணர் வழிகாட்டுதல்",
    searchAdvicePlaceholder: "ஆலோசனை தலைப்புகளைத் தேடுங்கள்...",
    allTopics: "அனைத்து தலைப்புகள்",
    soilCategory: "மண்",
    irrigationCategory: "பாசனம்",
    pestControlCategory: "பூச்சி கட்டுப்பாடு",
    fertilizersCategory: "உரங்கள்",
    harvestCategory: "அறுவடை",
    showingArticles: "காட்டுகிறது",
    articles: "கட்டுரைகள்",
    noArticlesFound: "கட்டுரைகள் எதுவும் கிடைக்கவில்லை",
    tryDifferentSearch: "வேறு தேடல் சொல்லை முயற்சிக்கவும்",
    readTime: "படிக்க",
    soilHealth: "மண் ஆரோக்கியம்",
    waterManagement: "தண்ணீர் மேலாண்மை",
    pestManagement: "பூச்சி மேலாண்மை",
    soilImprovement: "மண் மேம்பாடு",
    beginner: "தொடக்கத்தில்",
    intermediate: "இடைத்தரம்",
    advanced: "மேம்பட்ட",
  },
  te: {
    // Navbar
    home: "హోమ్",
    weather: "వాతావరణం",
    aiChat: "AI చాట్",
    crops: "పంటలు",
    advice: "సలహా",
    dashboard: "డాష్‌బోర్డ్",
    login: "లాగిన్",
    logout: "లాగ్అవుట్",
    getStarted: "ప్రారంభించండి",
    
    // Home
    builtForFarmers: "🌾 భారతీయ రైతుల కోసం",
    smartFarmingStartsHere: "స్మార్ట్ వ్యవసాయం",
    startsHere: "ఇక్కడ ప్రారంభమవుతుంది",
    heroDesc: "కృషిమిత్ర ప్రతి రైతుకు నైపుణ్య సలహా, లైవ్ వాతావరణం మరియు పంట మార్గనిర్దేశాలను అందిస్తుంది — నేరుగా మీ ఫోన్ నుండి. అనుభవం అవసరం లేదు.",
    startForFree: "ఉచితంగా ప్రారంభించండి →",
    tryAIChat: "AI చాట్ ప్రయత్నించండి",
    farmersHelped: "రైతులకు సహాయం చేశారు",
    cropTypes: "పంట రకాలు",
    aiAvailable: "AI అందుబాటులో ఉంది",
    toUse: "ఉపయోగించడానికి",
    everythingFarmerNeeds: "రైతుకు కావాల్సినవన్నీ",
    onePlatform: "మీ అన్ని వ్యవసాయ ప్రశ్నలు మరియు నిర్ణయాలకు ఒక ప్లాట్‌ఫారమ్.",
    aiFarmingAssistant: "AI వ్యవసాయ సహాయకుడు",
    aiFarmingDesc: "మీ భాషలో మీ పంటలు, నేల లేదా వ్యవసాయ పద్ధతుల గురించి ఏదైనా అడగండి.",
    liveWeather: "లైవ్ వాతావరణ సమాచారం",
    liveWeatherDesc: "మీ ఖచ్చితమైన స్థానానికి రియల్-టైమ్ వాతావరణ అప్‌డేట్‌లు మరియు అంచనాలను పొందండి.",
    cropRecommendations: "పంట సిఫార్సులు",
    cropRecommendationsDesc: "మీ నేల రకం మరియు సీజన్ ఆధారంగా ఏ పంటలు పండించాలో తెలుసుకోండి.",
    farmingAdvice: "వ్యవసాయ సలహా",
    farmingAdviceDesc: "నీటిపారుదల, ఎరువులు మరియు ఉత్తమ పద్ధతులపై నిపుణుల చిట్కాలు పొందండి.",
    trustedReliable: "విశ్వసనీయమైనది",
    trustedReliableDesc: "స్థానిక జ్ఞానంతో ప్రత్యేకంగా భారతీయ రైతుల కోసం నిర్మించబడింది.",
    voiceSupport: "వాయిస్ సపోర్ట్ (త్వరలో వస్తోంది)",
    voiceSupportDesc: "హిందీ లేదా మీ ప్రాంతీయ భాషలో AI అసిస్టెంట్‌తో మాట్లాడండి.",
    readyToFarm: "స్మార్ట్ వ్యవసాయానికి సిద్ధంగా ఉన్నారా?",
    joinThousands: "ఇప్పటికే కృషిమిత్రను ఉపయోగిస్తున్న వేలాది రైతులతో చేరండి.",
    createFreeAccount: "ఉచిత ఖాతాను సృష్టించండి →",
    builtWithLove: "భారతీయ రైతుల కోసం ❤️ తో నిర్మించబడింది",
    
    // Login
    welcomeBack: "తిరిగి స్వాగతం",
    loginToAccount: "మీ కృషిమిత్ర ఖాతాలోకి లాగిన్ అవ్వండి",
    phoneNumber: "ఫోన్ నంబర్",
    phonePlaceholder: "మీ నమోదిత ఫోన్ నంబర్",
    password: "పాస్‌వర్డ్",
    passwordPlaceholder: "మీ పాస్‌వర్డ్‌ను నమోదు చేయండి",
    loginButton: "కృషిమిత్రలో లాగిన్ అవ్వండి",
    loggingIn: "లాగిన్ అవుతోంది...",
    or: "లేదా",
    tryDemo: "🌾 డెమో ఖాతాను ప్రయత్నించండి",
    newToKrishiMitra: "కృషిమిత్రలో కొత్తవారా?",
    createFreeAccountLink: "ఉచిత ఖాతాను సృష్టించండి",
    
    // Register
    createAccount: "ఖాతాను సృష్టించండి",
    joinKrishiMitra: "కృషిమిత్రలో చేరండి — ఇది ఎప్పుడూ ఉచితం",
    fullName: "పూర్తి పేరు",
    fullNamePlaceholder: "మీ పూర్తి పేరును నమోదు చేయండి",
    phonePlaceholderReg: "10 అంకెల మొబైల్ నంబర్",
    state: "రాష్ట్రం",
    select: "ఎంచుకోండి",
    district: "జిల్లా",
    districtPlaceholder: "మీ జిల్లా",
    createStrongPassword: "బలమైన పాస్‌వర్డ్‌ను సృష్టించండి",
    createAccountButton: "నా ఖాతాను సృష్టించండి",
    creatingAccount: "ఖాతాను సృష్టిస్తోంది...",
    alreadyHaveAccount: "ఇప్పటికే ఖాతా ఉందా?",
    loginHere: "ఇక్కడ లాగిన్ అవ్వండి",
    
    // Chat
    aiFarmingAssistantTitle: "AI వ్యవసాయ సహాయకుడు",
    askAboutFarming: "వ్యవసాయం, పంటలు లేదా వ్యవసాయం గురించి ఏదైనా అడగండి",
    quickQuestions: "త్వరిత ప్రశ్నలు",
    askAboutCrops: "పంటలు, నేల, ఎరువుల గురించి అడగండి...",
    pressEnter: "పంపడానికి Enter నొక్కండి · కొత్త లైన్ కోసం Shift+Enter",
    welcomeMessage: "నమస్కారం! 🙏 నేను కృషిమిత్ర, మీ స్మార్ట్ వ్యవసాయ సహాయకుడిని. పంటలు, నేల, వాతావరణం, ఎరువులు లేదా వ్యవసాయ పద్ధతుల గురించి నాతో ఏదైనా అడగండి. నేను సహాయం చేయడానికి ఇక్కడ ఉన్నాను!",
    
    // Suggestions
    whichCropsJune: "జూన్ నెలలో ఏ పంటలు పంవాలి?",
    increaseWheatYield: "గోధుమ దిగుబడిని ఎలా పెంచవచ్చు?",
    fertilizerRice: "వరి పంటలకు ఉత్తమ ఎరువు?",
    protectPests: "పంటలను కీటకాల నుండి ఎలా కాపాడాలి?",
    whenIrrigate: "నా పొలానికి నీటిపారుదల ఎప్పుడు చేయాలి?",
    soilTomatoes: "టమాటాలకు ఉత్తమ నేల ఏది?",

    // Crops Page
    cropGuide: "పంట గైడ్",
    cropGuideDesc: "సీజన్ వారీ సమాచారం, MSP ధరలు & వ్యవసాయ చిట్కాలు",
    yourSoil: "మీ నేల:",
    suitableCrops: "సూక్తమైన పంటలు హైలైట్ చేయబడ్డాయి",
    filterByMySoil: "నా నేలతో ఫిల్టర్ చేయండి",
    searchPlaceholder: "పంట పేరు, హిందీ పేరు, లేదా నేల రకంతో వెతకండి...",
    season: "సీజన్",
    waterNeed: "నీటి అవసరం",
    soilType: "నేల రకం",
    showing: "చూపిస్తోంది",
    crops: "పంటలు",
    filteredBy: "· ఫిల్టర్ చేయబడింది",
    soil: "నేల",
    suitableForYour: "✓ మీ కోసం సూక్తమైన",
    soil: "నేల",
    temp: "ఉష్ణోగ్రత",
    water: "నీరు",
    duration: "వ్యవధి",
    mspPrice: "MSP ధర",
    avgYield: "సగటు దిగుబడి",
    growing: "పండిస్తోంది:",
    hideDetails: "వివరాలను దాచు",
    fullDetails: "పూర్తి వివరాలు",
    bestStates: "ఉత్తమ రాష్ట్రాలు",
    commonPests: "సాధారణ తెగుళ్ళు / వ్యాధులు",
    farmingTips: "వ్యవసాయ చిట్కాలు",
    profitPotential: "లాభం సామర్థ్యం",
    noCropsMatch: "మీ ఫిల్టర్‌లకు పంటలు సరిపోలడలేదు",
    tryClearing: "ఫిల్టర్‌ను తొలగించడానికి ప్రయత్నించండి లేదా శోధనను మార్చండి",
    clearAllFilters: "అన్ని ఫిల్టర్‌లను తొలగించండి",

    // Advice Page
    farmingAdviceTitle: "వ్యవసాయ సలహా",
    farmingAdviceDesc: "నేల, నీటిపారుదల, తెగుళ్ళు, ఎరువులు మరియు మరిన్నింటిలో లోతైన నిపుణుల మార్గదర్శనం",
    searchAdvicePlaceholder: "సలహా అంశాలను వెతకండి...",
    allTopics: "అన్ని అంశాలు",
    soilCategory: "నేల",
    irrigationCategory: "నీటిపారుదల",
    pestControlCategory: "తెగుల నియంత్రణ",
    fertilizersCategory: "ఎరువులు",
    harvestCategory: "పంట కోతలు",
    showingArticles: "చూపిస్తోంది",
    articles: "వ్యాసాలు",
    noArticlesFound: "వ్యాసాలు కనుగొనబడలేదు",
    tryDifferentSearch: "వేరే శోధన పదాన్ని ప్రయత్నించండి",
    readTime: "చదవడానికి",
    soilHealth: "నేల ఆరోగ్యం",
    waterManagement: "నీటి నిర్వహణ",
    pestManagement: "తెగుల నిర్వహణ",
    soilImprovement: "నేల మెరుగుదల",
    beginner: "ప్రారంభకుడు",
    intermediate: "మధ్యస్థం",
    advanced: "ఉన్నత",
  },
  bn: {
    // Navbar
    home: "হোম",
    weather: "আবহাওয়া",
    aiChat: "AI চ্যাট",
    crops: "ফসল",
    advice: "পরামর্শ",
    dashboard: "ড্যাশবোর্ড",
    login: "লগইন",
    logout: "লগআউট",
    getStarted: "শুরু করুন",
    
    // Home
    builtForFarmers: "🌾 ভারতীয কৃষকদের জন্য",
    smartFarmingStartsHere: "স্মার্ট কৃষি",
    startsHere: "এখান থেকে শুরু",
    heroDesc: "কৃষিমিত্র প্রতিটি কৃষককে বিশেষজ্ঞ পরামর্শ, লাইভ আবহাওয়া এবং ফসল নির্দেশনা প্রদান করে — সরাসরি আপনার ফোন থেকে। কোনো অভিজ্ঞতার প্রয়োজন নেই।",
    startForFree: "বিনামূল্যে শুরু করুন →",
    tryAIChat: "AI চ্যাট চেষ্টা করুন",
    farmersHelped: "কৃষকদের সাহায্য করেছে",
    cropTypes: "ফসলের ধরন",
    aiAvailable: "AI উপলব্ধ",
    toUse: "ব্যবহার করতে",
    everythingFarmerNeeds: "কৃষকের যা প্রয়োজন",
    onePlatform: "আপনার সমস্ত কৃষি প্রশ্ন এবং সিদ্ধান্তের জন্য একটি প্ল্যাটফর্ম।",
    aiFarmingAssistant: "AI কৃষি সহকারী",
    aiFarmingDesc: "আপনার ভাষায় আপনার ফসল, মাটি বা কৃষি পদ্ধতি সম্পর্কে যেকোনো কিছু জিজ্ঞাসা করুন।",
    liveWeather: "লাইভ আবহাওয়া তথ্য",
    liveWeatherDesc: "আপনার সঠিক অবস্থানের জন্য রিয়েল-টাইম আবহাওয়া আপডেট এবং পূর্বাভাস পান।",
    cropRecommendations: "ফসলের সুপারিশ",
    cropRecommendationsDesc: "আপনার মাটির ধরন এবং ঋতুর ভিত্তিতে কোন ফসল চাষ করবেন তা জানুন।",
    farmingAdvice: "কৃষি পরামর্শ",
    farmingAdviceDesc: "সেচ, সার এবং সেরা অনুশীলন সম্পর্কে বিশেষজ্ঞ টিপস পান।",
    trustedReliable: "বিশ্বস্ত এবং নির্ভরযোগ্য",
    trustedReliableDesc: "স্থানীয় জ্ঞান সহ বিশেষভাবে ভারতীয় কৃষকদের জন্য তৈরি।",
    voiceSupport: "ভয়েস সাপোর্ট (শীঘ্রই আসছে)",
    voiceSupportDesc: "হিন্দি বা আপনার আঞ্চলিক ভাষায় AI সহকারীর সাথে কথা বলুন।",
    readyToFarm: "স্মার্ট কৃষির জন্য প্রস্তুত?",
    joinThousands: "ইতিমধ্যে কৃষিমিত্র ব্যবহার করা হাজার হাজার কৃষকের সাথে যোগ দিন।",
    createFreeAccount: "বিনামূল্যে অ্যাকাউন্ট তৈরি করুন →",
    builtWithLove: "ভারতীয় কৃষকদের জন্য ❤️ দিয়ে তৈরি",
    
    // Login
    welcomeBack: "স্বাগতম",
    loginToAccount: "আপনার কৃষিমিত্র অ্যাকাউন্টে লগইন করুন",
    phoneNumber: "ফোন নম্বর",
    phonePlaceholder: "আপনার নিবন্ধিত ফোন নম্বর",
    password: "পাসওয়ার্ড",
    passwordPlaceholder: "আপনার পাসওয়ার্ড লিখুন",
    loginButton: "কৃষিমিত্রে লগইন করুন",
    loggingIn: "লগইন হচ্ছে...",
    or: "অথবা",
    tryDemo: "🌾 ডেমো অ্যাকাউন্ট চেষ্টা করুন",
    newToKrishiMitra: "কৃষিমিত্রে নতুন?",
    createFreeAccountLink: "বিনামূল্যে অ্যাকাউন্ট তৈরি করুন",
    
    // Register
    createAccount: "অ্যাকাউন্ট তৈরি করুন",
    joinKrishiMitra: "কৃষিমিত্রে যোগ দিন — এটি চিরকাল বিনামূল্যে",
    fullName: "পূর্ণ নাম",
    fullNamePlaceholder: "আপনার পূর্ণ নাম লিখুন",
    phonePlaceholderReg: "10 সংখ্যার মোবাইল নম্বর",
    state: "রাজ্য",
    select: "নির্বাচন",
    district: "জেলা",
    districtPlaceholder: "আপনার জেলা",
    createStrongPassword: "একটি শক্তিশালী পাসওয়ার্ড তৈরি করুন",
    createAccountButton: "আমার অ্যাকাউন্ট তৈরি করুন",
    creatingAccount: "অ্যাকাউন্ট তৈরি হচ্ছে...",
    alreadyHaveAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    loginHere: "এখানে লগইন করুন",
    
    // Chat
    aiFarmingAssistantTitle: "AI কৃষি সহকারী",
    askAboutFarming: "কৃষি, ফসল বা কৃষি সম্পর্কে যেকোনো কিছু জিজ্ঞাসা করুন",
    quickQuestions: "দ্রুত প্রশ্ন",
    askAboutCrops: "ফসল, মাটি, সার সম্পর্কে জিজ্ঞাসা করুন...",
    pressEnter: "পাঠাতে Enter চাপুন · নতুন লাইনের জন্য Shift+Enter",
    welcomeMessage: "নমস্কার! 🙏 আমি কৃষিমিত্র, আপনার স্মার্ট কৃষি সহকারী। ফসল, মাটি, আবহাওয়া, সার বা কৃষি কৌশল সম্পর্কে আমার কাছে যেকোনো কিছু জিজ্ঞাসা করুন। আমি সাহায্য করতে এখানে আছি!",
    
    // Suggestions
    whichCropsJune: "জুন মাসে কোন ফসল চাষ করব?",
    increaseWheatYield: "গমের ফলন কীভাবে বাড়াব?",
    fertilizerRice: "ধানের ফসলের জন্য সেরা সার?",
    protectPests: "ফসল কীটপতঙ্গ থেকে কীভাবে রক্ষা করব?",
    whenIrrigate: "আমি কখন আমার জমিতে সেচ দেব?",
    soilTomatoes: "টমেটোর জন্য সেরা মাটি কী?",

    // Crops Page
    cropGuide: "ফসল গাইড",
    cropGuideDesc: "ঋতু অনুযায়ী তথ্য, MSP দাম ও কৃষি টিপস",
    yourSoil: "আপনার মাটি:",
    suitableCrops: "উপযুক্ত ফসল হাইলাইট করা হয়েছে",
    filterByMySoil: "আমার মাটি দিয়ে ফিল্টার করুন",
    searchPlaceholder: "ফসলের নাম, হিন্দি নাম, বা মাটির ধরন দিয়ে অনুসন্ধান করুন...",
    season: "ঋতু",
    waterNeed: "পানির প্রয়োজন",
    soilType: "মাটির ধরন",
    showing: "দেখাচ্ছে",
    crops: "ফসল",
    filteredBy: "· ফিল্টার করা হয়েছে",
    soil: "মাটি",
    suitableForYour: "✓ আপনার জন্য উপযুক্ত",
    soil: "মাটি",
    temp: "তাপমাত্রা",
    water: "পানি",
    duration: "সময়কাল",
    mspPrice: "MSP দাম",
    avgYield: "গড় ফলন",
    growing: "চাষ করছে:",
    hideDetails: "বিস্তারিত লুকান",
    fullDetails: "পূর্ণ বিস্তারিত",
    bestStates: "সেরা রাজ্য",
    commonPests: "সাধারণ কীটপতঙ্গ / রোগ",
    farmingTips: "কৃষি টিপস",
    profitPotential: "লাভের সম্ভাবনা",
    noCropsMatch: "আপনার ফিল্টারের সাথে কোন ফসল মেলে না",
    tryClearing: "ফিল্টার সাফ করার চেষ্টা করুন বা অনুসন্ধান পরিবর্তন করুন",
    clearAllFilters: "সব ফিল্টার সাফ করুন",

    // Advice Page
    farmingAdviceTitle: "কৃষি পরামর্শ",
    farmingAdviceDesc: "মাটি, সেচ, কীটপতঙ্গ, সার এবং আরও অনেক বিষযে গভীর বিশেষজ্ঞ নির্দেশনা",
    searchAdvicePlaceholder: "পরামর্শ বিষয় অনুসন্ধান করুন...",
    allTopics: "সব বিষয",
    soilCategory: "মাটি",
    irrigationCategory: "সেচ",
    pestControlCategory: "কীট নিয়ন্ত্রণ",
    fertilizersCategory: "সার",
    harvestCategory: "ফসল কাটা",
    showingArticles: "দেখাচ্ছে",
    articles: "নিবন্ধ",
    noArticlesFound: "কোন নিবন্ধ পাওয়া যায়নি",
    tryDifferentSearch: "একটি ভিন্ন অনুসন্ধান শব্দ চেষ্টা করুন",
    readTime: "পড়া",
    soilHealth: "মাটি স্বাস্থ্য",
    waterManagement: "পানি ব্যবস্থাপনা",
    pestManagement: "কীট ব্যবস্থাপনা",
    soilImprovement: "মাটি উন্নতি",
    beginner: "শুরুতে",
    intermediate: "মধ্যম",
    advanced: "উন্নত",
  },
  mr: {
    // Navbar
    home: "होम",
    weather: "हवामान",
    aiChat: "AI चॅट",
    crops: "पिके",
    advice: "सल्ला",
    dashboard: "डॅशबोर्ड",
    login: "लॉगिन",
    logout: "लॉगआउट",
    getStarted: "सुरू ",
    
    // Home
    builtForFarmers: "🌾 भारतीय शेतकऱ्यांसाठी",
    smartFarmingStartsHere: "स्मार्ट शेती",
    startsHere: "येथून सुरू",
    heroDesc: "कृषिमित्र प्रत्येक शेतकऱ्याला तज्ञ सल्ला, लाइव्ह हवामान आणि पिकांचे मार्गदर्शन देते — थेट तुमच्या फोनवरून. कोणताही अनुभव नक्कीच नाही.",
    startForFree: "विनामूल्य सुरू करा →",
    tryAIChat: "AI चॅट वापरा",
    farmersHelped: "शेतकऱ्यांना मदत केली",
    cropTypes: "पिकांचे प्रकार",
    aiAvailable: "AI उपलब्ध",
    toUse: "वापरण्यासाठी",
    everythingFarmerNeeds: "शेतकऱ्याला हवे असलेले सर्व",
    onePlatform: "तुमच्या सर्व शेती प्रश्नांसाठी आणि निर्णयांसाठी एक प्लॅटफॉर्म.",
    aiFarmingAssistant: "AI शेती सहाय्यक",
    aiFarmingDesc: "तुमच्या भाषेत तुमच्या पिकांबद्दल, मातीबद्दल किंवा शेती पद्धतींबद्दल काहीही विचारा.",
    liveWeather: "लाइव्ह हवामान माहिती",
    liveWeatherDesc: "तुमच्या नेमक्या ठिकाणासाठी रीअल-टाइम हवामान अपडेट्स आणि अंदाज मिळवा.",
    cropRecommendations: "पिकांची शिफारस",
    cropRecommendationsDesc: "तुमच्या मातीच्या प्रकाराआधारे आणि हंगामानुसार कोणती पिके लावावीत हे जाणून घ्या.",
    farmingAdvice: "शेती सल्ला",
    farmingAdviceDesc: "सिंचन, खते आणि सर्वोत्तम पद्धतींबद्दल तज्ञ टिप्स मिळवा.",
    trustedReliable: "विश्वासू आणि विश्वसनीय",
    trustedReliableDesc: "स्थानिक ज्ञानासह विशेषतः भारतीय शेतकऱ्यांसाठी बनवले आहे.",
    voiceSupport: "व्हॉइस सपोर्ट (लवकर येत आहे)",
    voiceSupportDesc: "हिंदी किंवा तुमच्या प्रादेशिक भाषेत AI सहाय्यकाशी बोला.",
    readyToFarm: "स्मार्ट शेतीसाठी तयार आहात?",
    joinThousands: "आधीपासून कृषिमित्र वापरणाऱ्या हजारो शेतकऱ्यांसोबत जुळा.",
    createFreeAccount: "विनामूल्य खाते तयार करा →",
    builtWithLove: "भारतीय शेतकऱ्यांसाठी ❤️ सह बनवले",
    
    // Login
    welcomeBack: "पुन्हा स्वागत आहे",
    loginToAccount: "तुमच्या कृषिमित्र खात्यात लॉगिन करा",
    phoneNumber: "फोन नंबर",
    phonePlaceholder: "तुमचा नोंदणीकृत फोन नंबर",
    password: "पासवर्ड",
    passwordPlaceholder: "तुमचा पासवर्ड टाका",
    loginButton: "कृषिमित्रवर लॉगिन करा",
    loggingIn: "लॉगिन होत आहे...",
    or: "किंवा",
    tryDemo: "🌾 डेमो खाते वापरून पहा",
    newToKrishiMitra: "कृषिमित्रवर नवीन आहात?",
    createFreeAccountLink: "विनामूल्य खाते तयार करा",
    
    // Register
    createAccount: "खाते तयार करा",
    joinKrishiMitra: "कृषिमित्रमध्ये सामील व्हा — हे नेहमीच विनामूल्य आहे",
    fullName: "पूर्ण नाव",
    fullNamePlaceholder: "तुमचे पूर्ण नाव टाका",
    phonePlaceholderReg: "10 अंकी मोबाईल नंबर",
    state: "राज्य",
    select: "निवडा",
    district: "जिल्हा",
    districtPlaceholder: "तुमचा जिल्हा",
    createStrongPassword: "मजबूत पासवर्ड तयार करा",
    createAccountButton: "माझे खाते तयार करा",
    creatingAccount: "खाते तयार होत आहे...",
    alreadyHaveAccount: "आधीपासून खाते आहे का?",
    loginHere: "येथे लॉगिन करा",
    
    // Chat
    aiFarmingAssistantTitle: "AI शेती सहाय्यक",
    askAboutFarming: "शेती, पिके किंवा शेतीबद्दल काहीही विचारा",
    quickQuestions: "जलद प्रश्न",
    askAboutCrops: "पिके, माती, खते बद्दल विचारा...",
    pressEnter: "पाठवण्यासाठी Enter दाबा · नवीन ओळीसाठी Shift+Enter",
    welcomeMessage: "नमस्कार! 🙏 मी कृषिमित्र आहे, तुमचा स्मार्ट शेती सहाय्यक. पिके, माती, हवामान, खते किंवा शेती तंत्रज्ञानाबद्दल माझ्याकडून काहीही विचारा. मी मदत करण्यासाठी येथे आहे!",
    
    // Suggestions
    whichCropsJune: "जून महिन्यात कोणती पिके लावावीत?",
    increaseWheatYield: "गहूचे उत्पन्न कसे वाढवावे?",
    fertilizerRice: "तांदूळ पिकांसाठी सर्वोत्तम खत?",
    protectPests: "पिकांची किडींपासून कशी रक्षा करावी?",
    whenIrrigate: "मी माझ्या शेताला पाणी कधी द्यावे?",
    soilTomatoes: "टोमॅटोसाठी सर्वोत्तम माती कोणती?",

    // Crops Page
    cropGuide: "पिके मार्गदर्शक",
    cropGuideDesc: "हंगामानुसार माहिती, MSP किंमती आणि शेती टिप्स",
    yourSoil: "तुमची माती:",
    suitableCrops: "योग्य पिके हायलाइट केले",
    filterByMySoil: "माझ्या मातीनुसार फिल्टर करा",
    searchPlaceholder: "पिकाचे नाव, हिंदी नाव, किंवा मातीच्या प्रकारानुसार शोधा...",
    season: "हंगाम",
    waterNeed: "पाण्याची गरज",
    soilType: "मातीचा प्रकार",
    showing: "दाखवत आहे",
    crops: "पिके",
    filteredBy: "· फिल्टर केले",
    soil: "माती",
    suitableForYour: "✓ तुमच्यासाठी योग्य",
    soil: "माती",
    temp: "तापमान",
    water: "पाणी",
    duration: "कालावधी",
    mspPrice: "MSP किंमत",
    avgYield: "सरासरी उत्पादन",
    growing: "लागवत:",
    hideDetails: "तपशील लपवा",
    fullDetails: "पूर्ण तपशील",
    bestStates: "उत्तम राज्ये",
    commonPests: "सामान्य किडे / रोग",
    farmingTips: "शेती टिप्स",
    profitPotential: "नफ्याची शक्यता",
    noCropsMatch: "तुमच्या फिल्टरशी कोणतीही पिके जुळत नाहीत",
    tryClearing: "फिल्टर साफ करण्याचा प्रयत्न करा किंवा शोध बदला",
    clearAllFilters: "सर्व फिल्टर साफ करा",

    // Advice Page
    farmingAdviceTitle: "शेती सल्ला",
    farmingAdviceDesc: "माती, सिंचन, किडे, खते आणि आणखी बऱ्यावर तज्ञ मार्गदर्शन",
    searchAdvicePlaceholder: "सल्ला विषयांचा शोध घ्या...",
    allTopics: "सर्व विषय",
    soilCategory: "माती",
    irrigationCategory: "सिंचन",
    pestControlCategory: "किडे नियंत्रण",
    fertilizersCategory: "खते",
    harvestCategory: "लागदारी",
    showingArticles: "दाखवत आहे",
    articles: "लेख",
    noArticlesFound: "कोणतेही लेख सापडले नाहीत",
    tryDifferentSearch: "वेगळा शोध शब्द वापरा",
    readTime: "वाचण्यासाठी",
    soilHealth: "माती आरोग्य",
    waterManagement: "पाणी व्यवस्थापन",
    pestManagement: "किडे व्यवस्थापन",
    soilImprovement: "माती सुधारणा",
    beginner: "सुरुवाती",
    intermediate: "मध्यम",
    advanced: "प्रगत",
  },
}

const useLanguageStore = create((set) => ({
  language: 'en',
  setLanguage: (lang) => set({ language: lang }),
  t: (key) => {
    const lang = useLanguageStore.getState().language
    return translations[lang]?.[key] || translations['en'][key] || key
  }
}))

export default useLanguageStore
