import { create } from 'zustand'

const translations = {
  en: {
    // Navbar
    home: "Home",
    weather: "Weather",
    aiChat: "AI Chat",
    crops: "Crops",
    advice: "Advice",
    dashboard: "Dashboard",
    login: "Login",
    logout: "Logout",
    getStarted: "Get Started",
    
    // Home
    builtForFarmers: "🌾 Built for Indian Farmers",
    smartFarmingStartsHere: "Smart Farming",
    startsHere: "Starts Here",
    heroDesc: "KrishiMitra gives every farmer access to expert advice, live weather, and crop guidance — right from your phone. No experience needed.",
    startForFree: "Start for Free ",
    tryAIChat: "Try AI Chat",
    farmersHelped: "Farmers Helped",
    cropTypes: "Crop Types",
    aiAvailable: "AI Available",
    toUse: "To Use",
    everythingFarmerNeeds: "Everything a Farmer Needs",
    onePlatform: "One platform for all your farming questions and decisions.",
    aiFarmingAssistant: "AI Farming Assistant",
    aiFarmingDesc: "Ask anything about your crops, soil, or farming practices in your language.",
    liveWeather: "Live Weather Info",
    liveWeatherDesc: "Get real-time weather updates and forecasts for your exact location.",
    cropRecommendations: "Crop Recommendations",
    cropRecommendationsDesc: "Know which crops to grow based on your soil type and season.",
    farmingAdvice: "Farming Advice",
    farmingAdviceDesc: "Get expert tips on irrigation, fertilizers, and best practices.",
    trustedReliable: "Trusted & Reliable",
    trustedReliableDesc: "Built specifically for Indian farmers with local knowledge.",
    voiceSupport: "Voice Support (Soon)",
    voiceSupportDesc: "Talk to the AI assistant in Hindi or your regional language.",
    readyToFarm: "Ready to farm smarter?",
    joinThousands: "Join thousands of farmers already using KrishiMitra.",
    createFreeAccount: "Create Free Account →",
    builtWithLove: "Built with ❤️ for Indian Farmers",
    
    // Login
    welcomeBack: "Welcome Back",
    loginToAccount: "Login to your KrishiMitra account",
    phoneNumber: "Phone Number",
    phonePlaceholder: "Your registered phone number",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    loginButton: "Login to KrishiMitra",
    loggingIn: "Logging in...",
    or: "or",
    tryDemo: "🌾 Try Demo Account",
    newToKrishiMitra: "New to KrishiMitra?",
    createFreeAccountLink: "Create free account",
    
    // Register
    createAccount: "Create Account",
    joinKrishiMitra: "Join KrishiMitra — it's free forever",
    fullName: "Full Name",
    fullNamePlaceholder: "Enter your full name",
    phonePlaceholderReg: "10-digit mobile number",
    state: "State",
    select: "Select",
    district: "District",
    districtPlaceholder: "Your district",
    createStrongPassword: "Create a strong password",
    createAccountButton: "Create My Account",
    creatingAccount: "Creating Account...",
    alreadyHaveAccount: "Already have an account?",
    loginHere: "Login here",
    
    // Chat
    aiFarmingAssistantTitle: "AI Farming Assistant",
    askAboutFarming: "Ask anything about farming, crops, or agriculture",
    quickQuestions: "QUICK QUESTIONS",
    askAboutCrops: "Ask about crops, soil, fertilizers...",
    pressEnter: "Press Enter to send · Shift+Enter for new line",
    welcomeMessage: "Namaste! 🙏 I am KrishiMitra, your smart farming assistant. Ask me anything about crops, soil, weather, fertilizers, or farming techniques. I am here to help!",
    
    // Suggestions
    whichCropsJune: "Which crops should I grow in June?",
    increaseWheatYield: "How to increase wheat yield?",
    fertilizerRice: "Best fertilizer for rice crops?",
    protectPests: "How to protect crops from pests?",
    whenIrrigate: "When should I irrigate my field?",
    soilTomatoes: "What is the best soil for tomatoes?",

    // Crops Page
    cropGuide: "Crop Guide",
    cropGuideDesc: "Season-wise info, MSP prices & farming tips",
    yourSoil: "Your soil:",
    suitableCrops: "suitable crops highlighted",
    filterByMySoil: "Filter by my soil",
    searchPlaceholder: "Search by crop name, Hindi name, or soil type...",
    season: "SEASON",
    waterNeed: "WATER NEED",
    soilType: "SOIL TYPE",
    showing: "Showing",
    crops: "crops",
    filteredBy: "· filtered by",
    soil: "soil",
    suitableForYour: "✓ Suitable for your",
    soil: "soil",
    temp: "Temp",
    water: "Water",
    duration: "Duration",
    mspPrice: "MSP Price",
    avgYield: "Avg Yield",
    growing: "Growing:",
    hideDetails: "Hide details",
    fullDetails: "Full details",
    bestStates: "Best States",
    commonPests: "Common Pests / Diseases",
    farmingTips: "Farming Tips",
    profitPotential: "Profit Potential",
    noCropsMatch: "No crops match your filters",
    tryClearing: "Try clearing a filter or changing your search",
    clearAllFilters: "Clear all filters",

    // Advice Page
    farmingAdviceTitle: "Farming Advice",
    farmingAdviceDesc: "In-depth expert guidance on soil, irrigation, pests, fertilizers and more",
    searchAdvicePlaceholder: "Search advice topics...",
    allTopics: "All Topics",
    soilCategory: "Soil",
    irrigationCategory: "Irrigation",
    pestControlCategory: "Pest Control",
    fertilizersCategory: "Fertilizers",
    harvestCategory: "Harvest",
    showingArticles: "Showing",
    articles: "articles",
    noArticlesFound: "No articles found",
    tryDifferentSearch: "Try a different search term",
    readTime: "read",
    soilHealth: "Soil Health",
    waterManagement: "Water Management",
    pestManagement: "Pest Management",
    soilImprovement: "Soil Improvement",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",

    // Filter labels (Crops page)
    filterAll: "All",
    seasonKharif: "Kharif",
    seasonRabi: "Rabi",
    seasonAnnual: "Annual",
    waterLow: "Low",
    waterMedium: "Medium",
    waterHigh: "High",
    soilClay: "Clay",
    soilSandy: "Sandy",
    soilLoamy: "Loamy",
    soilBlackCotton: "Black Cotton",
    soilRed: "Red",
    soilAlluvial: "Alluvial",
    soilSandyLoam: "Sandy Loam",
    profitHigh: "High",
    profitMedium: "Medium",
    profitHighVolatile: "High (volatile)",
    profitMediumVolatile: "Medium (volatile)",

    // Dashboard
    dashWelcome: "Welcome 🌱",
    dashAskPrompt: "How can KrishiMitra help today?",
    dashWeather: "Weather",
    dashNoLocationSet: "No location set yet",
    dashCheckWeatherCity: "Check weather for a city →",
    dashFetchingWeather: "Fetching live weather…",
    dashCouldNotLoadWeather: "Could not load weather right now",
    dashHumiditySuffix: "humidity",
    dashFarmProfile: "Farm Profile",
    dashNotStarted: "Not started",
    dashInProgress: "In progress",
    dashComplete: "Complete",
    dashYourCrops: "Your Crops",
    dashNoCropsAdded: "No crops added yet",
    dashAddYourCrops: "Add your crops →",
    dashWhatDoYouNeed: "What do you need today?",
    dashFeatureChatTitle: "AI Chat",
    dashFeatureChatDesc: "Ask anything about farming",
    dashFeaturePlantDoctorTitle: "Plant Doctor",
    dashFeaturePlantDoctorDesc: "Scan a plant to identify diseases",
    plantDoctor: "Plant Doctor",
    pdTitle: "Plant Doctor",
    pdSubtitle: "Upload a clear photo of a plant leaf for an AI-assisted diagnosis.",
    pdUploadLabel: "Upload a plant photo",
    pdUploadHint: "Use a clear, well-lit image of the affected leaf or plant.",
    pdCropNameLabel: "Crop name (optional)",
    pdCropNamePlaceholder: "For example: Tomato",
    pdSelectImageFirst: "Please select a plant image first.",
    pdAnalyzeBtn: "Analyze plant",
    pdAnalyzing: "Analyzing…",
    pdChangeImage: "Change",
    pdError: "We could not analyze this image. Please try again.",
    pdResultHealthy: "Plant appears healthy",
    pdResultDiseased: "Disease or pest issue detected",
    pdConfidence: "Confidence",
    pdDescription: "Assessment",
    pdOrganicTreatment: "Organic treatment",
    pdChemicalTreatment: "Chemical treatment",
    pdPrevention: "Prevention tips",
    pdScanAnother: "Scan another plant",
    pdHistoryTitle: "Recent scans",
    pdHistoryEmpty: "Your completed plant scans will appear here.",
    dashFeatureWeatherTitle: "Weather",
    dashFeatureWeatherDesc: "Live weather for your area",
    dashFeatureCropsTitle: "Crops",
    dashFeatureCropsDesc: "Best crops for your soil",
    dashFeatureAdviceTitle: "Advice",
    dashFeatureAdviceDesc: "Expert farming tips",
    dashFeatureFarmProfileTitle: "Farm Profile",
    dashFeatureFarmProfileDesc: "Your soil, size & crops",

    // Farm Profile
    fpTitle: "🌾 Farm Profile",
    fpSubtitle: "This info helps AI give you better advice",
    fpSoilType: "Soil Type",
    fpFarmSize: "Farm Size (acres)",
    fpFarmSizePlaceholder: "e.g. 2.5",
    fpCropsYouGrow: "Crops You Grow",
    fpSaveButton: "Save Farm Profile",
    fpSaving: "Saving...",
    fpLoading: "Loading...",
    fpSaveSuccess: "✅ Profile saved! AI will now use this for better advice.",
    fpSaveFailed: "Failed to save. Please try again.",
    fpCropWheat: "Wheat",
    fpCropRice: "Rice",
    fpCropOnion: "Onion",
    fpCropCotton: "Cotton",
    fpCropSugarcane: "Sugarcane",
    fpCropSoybean: "Soybean",
    fpCropMaize: "Maize",
    fpCropTomato: "Tomato",
    fpCropPotato: "Potato",
    fpCropGram: "Gram",
    fpCropTurmeric: "Turmeric",
    fpCropGroundnut: "Groundnut",

    // Weather Page
    wxTitle: "Weather for Farmers",
    wxSubtitle: "Real-time weather and farming advice for your area",
    wxCityPlaceholder: "Enter your city or district...",
    wxSearch: "Search",
    wxPopularCities: "POPULAR CITIES",
    wxCityNotFound: "City not found. Please check spelling and try again.",
    wxFetching: "Fetching weather data...",
    wxFeelsLike: "Feels like",
    wxHumidity: "Humidity",
    wxWind: "Wind",
    wxVisibility: "Visibility",
    wxPressure: "Pressure",
    wxFarmingAdviceToday: "🌾 Farming Advice for Today",
    wxFiveDayForecast: "5-Day Forecast",
    wxSearchToSee: "Search your city to see weather",
    wxFreeData: "Free real-time data, no signup needed",
    wxClearSky: "Clear Sky",
    wxPartlyCloudy: "Partly Cloudy",
    wxFoggy: "Foggy",
    wxRainy: "Rainy",
    wxSnowfall: "Snowfall",
    wxRainShowers: "Rain Showers",
    wxThunderstorm: "Thunderstorm",
    wxCloudy: "Cloudy",
    wxAdviceStorm: "⛈️ Storm/heavy rain expected — secure equipment and avoid fieldwork today.",
    wxAdviceRain: "🌧️ Rain expected — avoid spraying fertilizers. Good time to check drainage.",
    wxAdviceHot: "☀️ Very hot day — irrigate early morning or evening. Keep livestock hydrated.",
    wxAdviceClear: "☀️ Clear sky — great day for spraying, harvesting, or field work.",
    wxAdviceCloudy: "⛅ Cloudy conditions — suitable for transplanting seedlings.",
    wxAdviceFoggy: "🌫️ Foggy conditions — wait for visibility to improve before field work.",
    wxAdviceDefault: "🌾 Check conditions before starting field work today.",
  },
  hi: {
    // Navbar
    home: "होम",
    weather: "मौसम",
    aiChat: "AI चैट",
    crops: "फसलें",
    advice: "सलाह",
    dashboard: "डैशबोर्ड",
    login: "लॉगिन",
    logout: "लॉगआउट",
    getStarted: "शुरू करें",
    
    // Home
    builtForFarmers: "🌾 भारतीय किसानों के लिए बनाया गया",
    smartFarmingStartsHere: "स्मार्ट खेती",
    startsHere: "यहाँ से शुरू करें",
    heroDesc: "कृषिमित्र हर किसान को विशेषज्ञ सलाह, लाइव मौसम, और फसल मार्गदर्शन तक पहुँच देता है — सीधे आपके फोन से। किसी अनुभव की आवश्यकता नहीं।",
    startForFree: "मुफ्त शुरू करें →",
    tryAIChat: "AI चैट आज़माएं",
    farmersHelped: "किसानों की मदद की",
    cropTypes: "फसल प्रकार",
    aiAvailable: "AI उपलब्ध",
    toUse: "उपयोग करने के लिए",
    everythingFarmerNeeds: "जो किसान को चाहिए",
    onePlatform: "अपने सभी खेती सवालों और निर्णयों के लिए एक प्लेटफ़ॉर्म।",
    aiFarmingAssistant: "AI खेती सहायक",
    aiFarmingDesc: "अपनी भाषा में अपनी फसलों, मिट्टी, या खेती प्रथाओं के बारे में कुछ भी पूछें।",
    liveWeather: "लाइव मौसम जानकारी",
    liveWeatherDesc: "अपने सटीक स्थान के लिए रीयल-टाइम मौसम अपडेट और पूर्वानुमान प्राप्त करें।",
    cropRecommendations: "फसल सिफारिशें",
    cropRecommendationsDesc: "अपनी मिट्टी के प्रकार और मौसम के आधार पर कौन सी फसलें उगानी हैं, जानें।",
    farmingAdvice: "खेती सलाह",
    farmingAdviceDesc: "सिंचाई, उर्वरकों और सर्वोत्तम प्रथाओं पर विशेषज्ञ सुझाव प्राप्त करें।",
    trustedReliable: "विश्वसनीय और भरोसेमंद",
    trustedReliableDesc: "स्थानीय ज्ञान के साथ विशेष रूप से भारतीय किसानों के लिए बनाया गया।",
    voiceSupport: "वॉइस सपोर्ट (जल्द आ रहा है)",
    voiceSupportDesc: "हिंदी या अपनी क्षेत्रीय भाषा में AI सहायक से बात करें।",
    readyToFarm: "स्मार्ट खेती के लिए तैयार हैं?",
    joinThousands: "पहले से कृषिमित्र का उपयोग कर रहे हजारों किसानों से जुड़ें।",
    createFreeAccount: "मुफ्त खाता बनाएं →",
    builtWithLove: "भारतीय किसानों के लिए ❤️ से बनाया गया",
    
    // Login
    welcomeBack: "वापसी पर स्वागत है",
    loginToAccount: "अपने कृषिमित्र खाते में लॉगिन करें",
    phoneNumber: "फोन नंबर",
    phonePlaceholder: "आपका पंजीकृत फोन नंबर",
    password: "पासवर्ड",
    passwordPlaceholder: "अपना पासवर्ड दर्ज करें",
    loginButton: "कृषिमित्र में लॉगिन करें",
    loggingIn: "लॉगिन हो रहा है...",
    or: "या",
    tryDemo: "🌾 डेमो खाता आज़माएं",
    newToKrishiMitra: "कृषिमित्र पर नए हैं?",
    createFreeAccountLink: "मुफ्त खाता बनाएं",
    
    // Register
    createAccount: "खाता बनाएं",
    joinKrishiMitra: "कृषिमित्र से जुड़ें — यह हमेशा मुफ्त है",
    fullName: "पूरा नाम",
    fullNamePlaceholder: "अपना पूरा नाम दर्ज करें",
    phonePlaceholderReg: "10 अंकों का मोबाइल नंबर",
    state: "राज्य",
    select: "चुनें",
    district: "जिला",
    districtPlaceholder: "आपका जिला",
    createStrongPassword: "एक मजबूत पासवर्ड बनाएं",
    createAccountButton: "मेरा खाता बनाएं",
    creatingAccount: "खाता बनाया जा रहा है...",
    alreadyHaveAccount: "पहले से खाता है?",
    loginHere: "यहाँ लॉगिन करें",
    
    // Chat
    aiFarmingAssistantTitle: "AI खेती सहायक",
    askAboutFarming: "खेती, फसलों या कृषि के बारे में कुछ भी पूछें",
    quickQuestions: "त्वरित प्रश्न",
    askAboutCrops: "फसलों, मिट्टी, उर्वरकों के बारे में पूछें...",
    pressEnter: "भेजने के लिए Enter दबाएं · नई लाइन के लिए Shift+Enter",
    welcomeMessage: "नमस्ते! 🙏 मैं कृषिमित्र हूं, आपका स्मार्ट खेती सहायक। फसलों, मिट्टी, मौसम, उर्वरकों या खेती तकनीकों के बारे में मुझसे कुछ भी पूछें। मैं यहाँ मदद करने के लिए हूं!",
    
    // Suggestions
    whichCropsJune: "जून में कौन सी फसलें उगानी चाहिए?",
    increaseWheatYield: "गेहूं की पैदावार कैसे बढ़ाएं?",
    increaseWheatYield: "गेहूं की पैदावार कैसे बढ़ाएं?",
    fertilizerRice: "चावल की फसल के लिए सबसे अच्छा उर्वरक?",
    protectPests: "फसलों की कीटों से सुरक्षा कैसे करें?",
    whenIrrigate: "मुझे अपने खेत की सिंचाई कब करनी चाहिए?",
    soilTomatoes: "टमाटर के लिए सबसे अच्छी मिट्टी क्या है?",

    // Crops Page
    cropGuide: "फसल गाइड",
    cropGuideDesc: "मौसम-वार जानकारी, MSP कीमतें और खेती टिप्स",
    yourSoil: "आपकी मिट्टी:",
    suitableCrops: "उपयुक्त फसलें हाइलाइट की गई",
    filterByMySoil: "मेरी मिट्टी से फ़िल्टर करें",
    searchPlaceholder: "फसल का नाम, हिंदी नाम, या मिट्टी के प्रकार से खोजें...",
    season: "मौसम",
    waterNeed: "पानी की जरूरत",
    soilType: "मिट्टी का प्रकार",
    showing: "दिखा रहा है",
    crops: "फसलें",
    filteredBy: "· फ़िल्टर किया गया",
    soil: "मिट्टी",
    suitableForYour: "✓ आपकी के लिए उपयुक्त",
    soil: "मिट्टी",
    temp: "तापमान",
    water: "पानी",
    duration: "अवधि",
    mspPrice: "MSP कीमत",
    avgYield: "औसत उपज",
    growing: "उगाना:",
    hideDetails: "विवरण छिपाएं",
    fullDetails: "पूरा विवरण",
    bestStates: "सर्वश्रेष्ठ राज्य",
    commonPests: "सामान्य कीट / रोग",
    farmingTips: "खेती टिप्स",
    profitPotential: "लाभ की संभावना",
    noCropsMatch: "कोई फसल आपके फ़िल्टर से मेल नहीं खाती",
    tryClearing: "फ़िल्टर साफ़ करने का प्रयास करें या खोज बदलें",
    clearAllFilters: "सभी फ़िल्टर साफ़ करें",

    // Advice Page
    farmingAdviceTitle: "खेती सलाह",
    farmingAdviceDesc: "मिट्टी, सिंचाई, कीट, उर्वरकों और अधिक पर गहन विशेषज्ञ मार्गदर्शन",
    searchAdvicePlaceholder: "सलाह विषयों की खोज करें...",
    allTopics: "सभी विषय",
    soilCategory: "मिट्टी",
    irrigationCategory: "सिंचाई",
    pestControlCategory: "कीट नियंत्रण",
    fertilizersCategory: "उर्वरक",
    harvestCategory: "फसल कटाई",
    showingArticles: "दिखा रहा है",
    articles: "लेख",
    noArticlesFound: "कोई लेख नहीं मिला",
    tryDifferentSearch: "एक अलग खोज शब्द आज़माएं",
    readTime: "पढ़ने का समय",
    soilHealth: "मिट्टी स्वास्थ्य",
    waterManagement: "पानी प्रबंधन",
    pestManagement: "कीट प्रबंधन",
    soilImprovement: "मिट्टी सुधार",
    beginner: "शुरुआती",
    intermediate: "मध्यम",
    advanced: "उन्नत",

    // Filter labels (Crops page)
    filterAll: "सभी",
    seasonKharif: "खरीफ",
    seasonRabi: "रबी",
    seasonAnnual: "वार्षिक",
    waterLow: "कम",
    waterMedium: "मध्यम",
    waterHigh: "अधिक",
    soilClay: "चिकनी मिट्टी",
    soilSandy: "बलुई",
    soilLoamy: "दोमट",
    soilBlackCotton: "काली कपासी मिट्टी",
    soilRed: "लाल मिट्टी",
    soilAlluvial: "जलोढ़",
    soilSandyLoam: "बलुई दोमट",
    profitHigh: "उच्च",
    profitMedium: "मध्यम",
    profitHighVolatile: "उच्च (अस्थिर)",
    profitMediumVolatile: "मध्यम (अस्थिर)",

    // Dashboard
    dashWelcome: "स्वागत है 🌱",
    dashAskPrompt: "कृषिमित्र आज कैसे मदद कर सकता है?",
    dashWeather: "मौसम",
    dashNoLocationSet: "अभी तक कोई स्थान सेट नहीं है",
    dashCheckWeatherCity: "किसी शहर का मौसम देखें →",
    dashFetchingWeather: "लाइव मौसम प्राप्त कर रहे हैं…",
    dashCouldNotLoadWeather: "अभी मौसम लोड नहीं हो सका",
    dashHumiditySuffix: "नमी",
    dashFarmProfile: "फार्म प्रोफाइल",
    dashNotStarted: "शुरू नहीं हुआ",
    dashInProgress: "प्रगति में",
    dashComplete: "पूर्ण",
    dashYourCrops: "आपकी फसलें",
    dashNoCropsAdded: "अभी तक कोई फसल नहीं जोड़ी गई",
    dashAddYourCrops: "अपनी फसलें जोड़ें →",
    dashWhatDoYouNeed: "आज आपको क्या चाहिए?",
    dashFeatureChatTitle: "AI चैट",
    dashFeatureChatDesc: "खेती के बारे में कुछ भी पूछें",
    dashFeaturePlantDoctorTitle: "प्लांट डॉक्टर",
    dashFeaturePlantDoctorDesc: "पौधे की बीमारी पहचानने के लिए स्कैन करें",
    plantDoctor: "प्लांट डॉक्टर",
    pdTitle: "प्लांट डॉक्टर",
    pdSubtitle: "AI सहायता से जांच के लिए पत्ते या पौधे की साफ तस्वीर अपलोड करें।",
    pdUploadLabel: "पौधे की तस्वीर अपलोड करें",
    pdUploadHint: "प्रभावित पत्ते या पौधे की साफ, अच्छी रोशनी वाली तस्वीर लें।",
    pdCropNameLabel: "फसल का नाम (वैकल्पिक)",
    pdCropNamePlaceholder: "उदाहरण: टमाटर",
    pdSelectImageFirst: "कृपया पहले पौधे की तस्वीर चुनें।",
    pdAnalyzeBtn: "पौधे का विश्लेषण करें",
    pdAnalyzing: "विश्लेषण हो रहा है…",
    pdChangeImage: "बदलें",
    pdError: "इस तस्वीर का विश्लेषण नहीं हो सका। फिर प्रयास करें।",
    pdResultHealthy: "पौधा स्वस्थ प्रतीत होता है",
    pdResultDiseased: "रोग या कीट की समस्या मिली",
    pdConfidence: "विश्वास",
    pdDescription: "आकलन",
    pdOrganicTreatment: "जैविक उपचार",
    pdChemicalTreatment: "रासायनिक उपचार",
    pdPrevention: "बचाव के उपाय",
    pdScanAnother: "दूसरे पौधे को स्कैन करें",
    pdHistoryTitle: "हाल की स्कैन",
    pdHistoryEmpty: "आपके पूरे किए गए पौधे स्कैन यहां दिखेंगे।",
    dashFeatureWeatherTitle: "मौसम",
    dashFeatureWeatherDesc: "आपके क्षेत्र का लाइव मौसम",
    dashFeatureCropsTitle: "फसलें",
    dashFeatureCropsDesc: "आपकी मिट्टी के लिए सर्वोत्तम फसलें",
    dashFeatureAdviceTitle: "सलाह",
    dashFeatureAdviceDesc: "विशेषज्ञ खेती युक्तियाँ",
    dashFeatureFarmProfileTitle: "फार्म प्रोफाइल",
    dashFeatureFarmProfileDesc: "आपकी मिट्टी, आकार और फसलें",

    // Farm Profile
    fpTitle: "🌾 फार्म प्रोफाइल",
    fpSubtitle: "यह जानकारी AI को बेहतर सलाह देने में मदद करती है",
    fpSoilType: "मिट्टी का प्रकार",
    fpFarmSize: "खेत का आकार (एकड़)",
    fpFarmSizePlaceholder: "जैसे 2.5",
    fpCropsYouGrow: "आप जो फसलें उगाते हैं",
    fpSaveButton: "फार्म प्रोफाइल सहेजें",
    fpSaving: "सहेजा जा रहा है...",
    fpLoading: "लोड हो रहा है...",
    fpSaveSuccess: "✅ प्रोफाइल सहेजी गई! AI अब बेहतर सलाह के लिए इसका उपयोग करेगा।",
    fpSaveFailed: "सहेजने में विफल। कृपया पुनः प्रयास करें।",
    fpCropWheat: "गेहूं",
    fpCropRice: "चावल",
    fpCropOnion: "प्याज",
    fpCropCotton: "कपास",
    fpCropSugarcane: "गन्ना",
    fpCropSoybean: "सोयाबीन",
    fpCropMaize: "मक्का",
    fpCropTomato: "टमाटर",
    fpCropPotato: "आलू",
    fpCropGram: "चना",
    fpCropTurmeric: "हल्दी",
    fpCropGroundnut: "मूंगफली",

    // Weather Page
    wxTitle: "किसानों के लिए मौसम",
    wxSubtitle: "आपके क्षेत्र के लिए रीयल-टाइम मौसम और खेती सलाह",
    wxCityPlaceholder: "अपना शहर या जिला दर्ज करें...",
    wxSearch: "खोजें",
    wxPopularCities: "लोकप्रिय शहर",
    wxCityNotFound: "शहर नहीं मिला। कृपया वर्तनी जांचें और पुनः प्रयास करें।",
    wxFetching: "मौसम डेटा प्राप्त कर रहे हैं...",
    wxFeelsLike: "महसूस होता है",
    wxHumidity: "नमी",
    wxWind: "हवा",
    wxVisibility: "दृश्यता",
    wxPressure: "दबाव",
    wxFarmingAdviceToday: "🌾 आज के लिए खेती सलाह",
    wxFiveDayForecast: "5-दिन का पूर्वानुमान",
    wxSearchToSee: "मौसम देखने के लिए अपना शहर खोजें",
    wxFreeData: "मुफ्त रीयल-टाइम डेटा, कोई साइनअप आवश्यक नहीं",
    wxClearSky: "साफ आसमान",
    wxPartlyCloudy: "आंशिक रूप से बादल",
    wxFoggy: "कोहरा",
    wxRainy: "बारिश",
    wxSnowfall: "बर्फबारी",
    wxRainShowers: "बौछारें",
    wxThunderstorm: "आंधी-तूफान",
    wxCloudy: "बादल",
    wxAdviceStorm: "⛈️ तूफान/भारी बारिश की संभावना — उपकरण सुरक्षित रखें और आज खेत का काम टालें।",
    wxAdviceRain: "🌧️ बारिश की संभावना — उर्वरक छिड़काव से बचें। जल निकासी जांचने का अच्छा समय है।",
    wxAdviceHot: "☀️ बहुत गर्म दिन — सुबह जल्दी या शाम को सिंचाई करें। पशुओं को हाइड्रेटेड रखें।",
    wxAdviceClear: "☀️ साफ आसमान — छिड़काव, कटाई या खेत के काम के लिए बढ़िया दिन।",
    wxAdviceCloudy: "⛅ बादल छाए हुए हैं — पौध रोपाई के लिए उपयुक्त।",
    wxAdviceFoggy: "🌫️ कोहरे की स्थिति — खेत का काम शुरू करने से पहले दृश्यता में सुधार का इंतज़ार करें।",
    wxAdviceDefault: "🌾 आज खेत का काम शुरू करने से पहले स्थिति जांच लें।",
  },
  mr: {
    // Navbar
    home: "होम",
    weather: "हवामान",
    aiChat: "AI चॅट",
    crops: "पिके",
    advice: "सल्ला",
    dashboard: "डॅशबोर्ड",
    login: "लॉगिन",
    logout: "लॉगआउट",
    getStarted: "सुरू ",
    
    // Home
    builtForFarmers: "🌾 भारतीय शेतकऱ्यांसाठी",
    smartFarmingStartsHere: "स्मार्ट शेती",
    startsHere: "येथून सुरू",
    heroDesc: "कृषिमित्र प्रत्येक शेतकऱ्याला तज्ञ सल्ला, लाइव्ह हवामान आणि पिकांचे मार्गदर्शन देते — थेट तुमच्या फोनवरून. कोणत्याही अनुभवाची गरज नाही.",
    startForFree: "विनामूल्य सुरू करा →",
    tryAIChat: "AI चॅट वापरा",
    farmersHelped: "शेतकऱ्यांना मदत केली",
    cropTypes: "पिकांचे प्रकार",
    aiAvailable: "AI उपलब्ध",
    toUse: "वापरण्यासाठी",
    everythingFarmerNeeds: "शेतकऱ्याला हवे असलेले सर्व",
    onePlatform: "तुमच्या सर्व शेती प्रश्नांसाठी आणि निर्णयांसाठी एक प्लॅटफॉर्म.",
    aiFarmingAssistant: "AI शेती सहाय्यक",
    aiFarmingDesc: "तुमच्या भाषेत तुमच्या पिकांबद्दल, मातीबद्दल किंवा शेती पद्धतींबद्दल काहीही विचारा.",
    liveWeather: "लाइव्ह हवामान माहिती",
    liveWeatherDesc: "तुमच्या नेमक्या ठिकाणासाठी रीअल-टाइम हवामान अपडेट्स आणि अंदाज मिळवा.",
    cropRecommendations: "पिकांची शिफारस",
    cropRecommendationsDesc: "तुमच्या मातीच्या प्रकाराआधारे आणि हंगामानुसार कोणती पिके लावावीत हे जाणून घ्या.",
    farmingAdvice: "शेती सल्ला",
    farmingAdviceDesc: "सिंचन, खते आणि सर्वोत्तम पद्धतींबद्दल तज्ञ टिप्स मिळवा.",
    trustedReliable: "विश्वासू आणि विश्वसनीय",
    trustedReliableDesc: "स्थानिक ज्ञानासह विशेषतः भारतीय शेतकऱ्यांसाठी बनवले आहे.",
    voiceSupport: "व्हॉइस सपोर्ट (लवकर येत आहे)",
    voiceSupportDesc: "हिंदी किंवा तुमच्या प्रादेशिक भाषेत AI सहाय्यकाशी बोला.",
    readyToFarm: "स्मार्ट शेतीसाठी तयार आहात?",
    joinThousands: "आधीपासून कृषिमित्र वापरणाऱ्या हजारो शेतकऱ्यांसोबत जुळा.",
    createFreeAccount: "विनामूल्य खाते तयार करा →",
    builtWithLove: "भारतीय शेतकऱ्यांसाठी ❤️ सह बनवले",
    
    // Login
    welcomeBack: "पुन्हा स्वागत आहे",
    loginToAccount: "तुमच्या कृषिमित्र खात्यात लॉगिन करा",
    phoneNumber: "फोन नंबर",
    phonePlaceholder: "तुमचा नोंदणीकृत फोन नंबर",
    password: "पासवर्ड",
    passwordPlaceholder: "तुमचा पासवर्ड टाका",
    loginButton: "कृषिमित्रवर लॉगिन करा",
    loggingIn: "लॉगिन होत आहे...",
    or: "किंवा",
    tryDemo: "🌾 डेमो खाते वापरून पहा",
    newToKrishiMitra: "कृषिमित्रवर नवीन आहात?",
    createFreeAccountLink: "विनामूल्य खाते तयार करा",
    
    // Register
    createAccount: "खाते तयार करा",
    joinKrishiMitra: "कृषिमित्रमध्ये सामील व्हा — हे नेहमीच विनामूल्य आहे",
    fullName: "पूर्ण नाव",
    fullNamePlaceholder: "तुमचे पूर्ण नाव टाका",
    phonePlaceholderReg: "10 अंकी मोबाईल नंबर",
    state: "राज्य",
    select: "निवडा",
    district: "जिल्हा",
    districtPlaceholder: "तुमचा जिल्हा",
    createStrongPassword: "मजबूत पासवर्ड तयार करा",
    createAccountButton: "माझे खाते तयार करा",
    creatingAccount: "खाते तयार होत आहे...",
    alreadyHaveAccount: "आधीपासून खाते आहे का?",
    loginHere: "येथे लॉगिन करा",
    
    // Chat
    aiFarmingAssistantTitle: "AI शेती सहाय्यक",
    askAboutFarming: "शेती, पिके किंवा शेतीबद्दल काहीही विचारा",
    quickQuestions: "जलद प्रश्न",
    askAboutCrops: "पिके, माती, खते बद्दल विचारा...",
    pressEnter: "पाठवण्यासाठी Enter दाबा · नवीन ओळीसाठी Shift+Enter",
    welcomeMessage: "नमस्कार! 🙏 मी कृषिमित्र आहे, तुमचा स्मार्ट शेती सहाय्यक. पिके, माती, हवामान, खते किंवा शेती तंत्रज्ञानाबद्दल माझ्याकडून काहीही विचारा. मी मदत करण्यासाठी येथे आहे!",
    
    // Suggestions
    whichCropsJune: "जून महिन्यात कोणती पिके लावावीत?",
    increaseWheatYield: "गहूचे उत्पन्न कसे वाढवावे?",
    fertilizerRice: "तांदूळ पिकांसाठी सर्वोत्तम खत?",
    protectPests: "पिकांची किडींपासून कशी रक्षा करावी?",
    whenIrrigate: "मी माझ्या शेताला पाणी कधी द्यावे?",
    soilTomatoes: "टोमॅटोसाठी सर्वोत्तम माती कोणती?",

    // Crops Page
    cropGuide: "पिके मार्गदर्शक",
    cropGuideDesc: "हंगामानुसार माहिती, MSP किंमती आणि शेती टिप्स",
    yourSoil: "तुमची माती:",
    suitableCrops: "योग्य पिके हायलाइट केले",
    filterByMySoil: "माझ्या मातीनुसार फिल्टर करा",
    searchPlaceholder: "पिकाचे नाव, हिंदी नाव, किंवा मातीच्या प्रकारानुसार शोधा...",
    season: "हंगाम",
    waterNeed: "पाण्याची गरज",
    soilType: "मातीचा प्रकार",
    showing: "दाखवत आहे",
    crops: "पिके",
    filteredBy: "· फिल्टर केले",
    soil: "माती",
    suitableForYour: "✓ तुमच्यासाठी योग्य",
    soil: "माती",
    temp: "तापमान",
    water: "पाणी",
    duration: "कालावधी",
    mspPrice: "MSP किंमत",
    avgYield: "सरासरी उत्पादन",
    growing: "लागवत:",
    hideDetails: "तपशील लपवा",
    fullDetails: "पूर्ण तपशील",
    bestStates: "उत्तम राज्ये",
    commonPests: "सामान्य किडे / रोग",
    farmingTips: "शेती टिप्स",
    profitPotential: "नफ्याची शक्यता",
    noCropsMatch: "तुमच्या फिल्टरशी कोणतीही पिके जुळत नाहीत",
    tryClearing: "फिल्टर साफ करण्याचा प्रयत्न करा किंवा शोध बदला",
    clearAllFilters: "सर्व फिल्टर साफ करा",

    // Advice Page
    farmingAdviceTitle: "शेती सल्ला",
    farmingAdviceDesc: "माती, सिंचन, किडे, खते आणि आणखी बऱ्यावर तज्ञ मार्गदर्शन",
    searchAdvicePlaceholder: "सल्ला विषयांचा शोध घ्या...",
    allTopics: "सर्व विषय",
    soilCategory: "माती",
    irrigationCategory: "सिंचन",
    pestControlCategory: "किडे नियंत्रण",
    fertilizersCategory: "खते",
    harvestCategory: "लागदारी",
    showingArticles: "दाखवत आहे",
    articles: "लेख",
    noArticlesFound: "कोणतेही लेख सापडले नाहीत",
    tryDifferentSearch: "वेगळा शोध शब्द वापरा",
    readTime: "वाचण्यासाठी",
    soilHealth: "माती आरोग्य",
    waterManagement: "पाणी व्यवस्थापन",
    pestManagement: "किडे व्यवस्थापन",
    soilImprovement: "माती सुधारणा",
    beginner: "सुरुवाती",
    intermediate: "मध्यम",
    advanced: "प्रगत",

    // Filter labels (Crops page)
    filterAll: "सर्व",
    seasonKharif: "खरीप",
    seasonRabi: "रब्बी",
    seasonAnnual: "वार्षिक",
    waterLow: "कमी",
    waterMedium: "मध्यम",
    waterHigh: "जास्त",
    soilClay: "चिकणमाती",
    soilSandy: "वाळूमिश्रित",
    soilLoamy: "गाळाची माती",
    soilBlackCotton: "काळी कसदार माती",
    soilRed: "लाल माती",
    soilAlluvial: "जलोढ माती",
    soilSandyLoam: "वाळूमिश्रित चिकणमाती",
    profitHigh: "जास्त",
    profitMedium: "मध्यम",
    profitHighVolatile: "जास्त (अस्थिर)",
    profitMediumVolatile: "मध्यम (अस्थिर)",

    // Dashboard
    dashWelcome: "स्वागत आहे 🌱",
    dashAskPrompt: "कृषिमित्र आज कशी मदत करू शकते?",
    dashWeather: "हवामान",
    dashNoLocationSet: "अद्याप कोणतेही ठिकाण सेट केलेले नाही",
    dashCheckWeatherCity: "एखाद्या शहराचे हवामान पहा →",
    dashFetchingWeather: "लाइव्ह हवामान मिळवत आहे…",
    dashCouldNotLoadWeather: "सध्या हवामान लोड करता आले नाही",
    dashHumiditySuffix: "आर्द्रता",
    dashFarmProfile: "फार्म प्रोफाइल",
    dashNotStarted: "सुरू झाले नाही",
    dashInProgress: "प्रगतीत",
    dashComplete: "पूर्ण",
    dashYourCrops: "तुमची पिके",
    dashNoCropsAdded: "अद्याप कोणतीही पिके जोडलेली नाहीत",
    dashAddYourCrops: "तुमची पिके जोडा →",
    dashWhatDoYouNeed: "आज तुम्हाला काय हवे आहे?",
    dashFeatureChatTitle: "AI चॅट",
    dashFeatureChatDesc: "शेतीबद्दल काहीही विचारा",
    dashFeaturePlantDoctorTitle: "प्लांट डॉक्टर",
    dashFeaturePlantDoctorDesc: "वनस्पतीचे रोग ओळखण्यासाठी स्कॅन करा",
    plantDoctor: "प्लांट डॉक्टर",
    pdTitle: "प्लांट डॉक्टर",
    pdSubtitle: "AI च्या मदतीने तपासणीसाठी पानाचा किंवा वनस्पतीचा स्पष्ट फोटो अपलोड करा.",
    pdUploadLabel: "वनस्पतीचा फोटो अपलोड करा",
    pdUploadHint: "बाधित पानाचा किंवा वनस्पतीचा स्पष्ट, चांगल्या प्रकाशातील फोटो वापरा.",
    pdCropNameLabel: "पिकाचे नाव (ऐच्छिक)",
    pdCropNamePlaceholder: "उदा.: टोमॅटो",
    pdSelectImageFirst: "कृपया प्रथम वनस्पतीचा फोटो निवडा.",
    pdAnalyzeBtn: "वनस्पतीचे विश्लेषण करा",
    pdAnalyzing: "विश्लेषण सुरू आहे…",
    pdChangeImage: "बदला",
    pdError: "या फोटोचे विश्लेषण करता आले नाही. कृपया पुन्हा प्रयत्न करा.",
    pdResultHealthy: "वनस्पती निरोगी दिसते",
    pdResultDiseased: "रोग किंवा किडीची समस्या आढळली",
    pdConfidence: "विश्वास",
    pdDescription: "मूल्यांकन",
    pdOrganicTreatment: "सेंद्रिय उपचार",
    pdChemicalTreatment: "रासायनिक उपचार",
    pdPrevention: "प्रतिबंधक सूचना",
    pdScanAnother: "दुसरी वनस्पती स्कॅन करा",
    pdHistoryTitle: "अलीकडील स्कॅन",
    pdHistoryEmpty: "तुमचे पूर्ण झालेले वनस्पती स्कॅन येथे दिसतील.",
    dashFeatureWeatherTitle: "हवामान",
    dashFeatureWeatherDesc: "तुमच्या परिसराचे लाइव्ह हवामान",
    dashFeatureCropsTitle: "पिके",
    dashFeatureCropsDesc: "तुमच्या मातीसाठी सर्वोत्तम पिके",
    dashFeatureAdviceTitle: "सल्ला",
    dashFeatureAdviceDesc: "तज्ञ शेती टिप्स",
    dashFeatureFarmProfileTitle: "फार्म प्रोफाइल",
    dashFeatureFarmProfileDesc: "तुमची माती, आकार आणि पिके",

    // Farm Profile
    fpTitle: "🌾 फार्म प्रोफाइल",
    fpSubtitle: "ही माहिती AI ला अधिक चांगला सल्ला देण्यास मदत करते",
    fpSoilType: "मातीचा प्रकार",
    fpFarmSize: "शेताचा आकार (एकर)",
    fpFarmSizePlaceholder: "उदा. 2.5",
    fpCropsYouGrow: "तुम्ही घेत असलेली पिके",
    fpSaveButton: "फार्म प्रोफाइल जतन करा",
    fpSaving: "जतन करत आहे...",
    fpLoading: "लोड होत आहे...",
    fpSaveSuccess: "✅ प्रोफाइल जतन झाली! AI आता अधिक चांगल्या सल्ल्यासाठी याचा वापर करेल.",
    fpSaveFailed: "जतन करण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा.",
    fpCropWheat: "गहू",
    fpCropRice: "भात",
    fpCropOnion: "कांदा",
    fpCropCotton: "कापूस",
    fpCropSugarcane: "ऊस",
    fpCropSoybean: "सोयाबीन",
    fpCropMaize: "मका",
    fpCropTomato: "टोमॅटो",
    fpCropPotato: "बटाटा",
    fpCropGram: "हरभरा",
    fpCropTurmeric: "हळद",
    fpCropGroundnut: "भुईमूग",

    // Weather Page
    wxTitle: "शेतकऱ्यांसाठी हवामान",
    wxSubtitle: "तुमच्या परिसरासाठी रीअल-टाइम हवामान आणि शेती सल्ला",
    wxCityPlaceholder: "तुमचे शहर किंवा जिल्हा टाका...",
    wxSearch: "शोधा",
    wxPopularCities: "लोकप्रिय शहरे",
    wxCityNotFound: "शहर सापडले नाही. कृपया स्पेलिंग तपासा आणि पुन्हा प्रयत्न करा.",
    wxFetching: "हवामान डेटा मिळवत आहे...",
    wxFeelsLike: "जाणवते",
    wxHumidity: "आर्द्रता",
    wxWind: "वारा",
    wxVisibility: "दृश्यमानता",
    wxPressure: "दाब",
    wxFarmingAdviceToday: "🌾 आजसाठी शेती सल्ला",
    wxFiveDayForecast: "5-दिवसांचा अंदाज",
    wxSearchToSee: "हवामान पाहण्यासाठी तुमचे शहर शोधा",
    wxFreeData: "मोफत रीअल-टाइम डेटा, नोंदणीची गरज नाही",
    wxClearSky: "निरभ्र आकाश",
    wxPartlyCloudy: "अंशतः ढगाळ",
    wxFoggy: "धुके",
    wxRainy: "पाऊस",
    wxSnowfall: "हिमवृष्टी",
    wxRainShowers: "पावसाच्या सरी",
    wxThunderstorm: "वादळ",
    wxCloudy: "ढगाळ",
    wxAdviceStorm: "⛈️ वादळ/मुसळधार पावसाची शक्यता — उपकरणे सुरक्षित ठेवा आणि आज शेतीचे काम टाळा.",
    wxAdviceRain: "🌧️ पावसाची शक्यता — खत फवारणी टाळा. निचरा तपासण्याची चांगली वेळ आहे.",
    wxAdviceHot: "☀️ खूप उष्ण दिवस — सकाळी लवकर किंवा संध्याकाळी सिंचन करा. जनावरांना हायड्रेटेड ठेवा.",
    wxAdviceClear: "☀️ निरभ्र आकाश — फवारणी, कापणी किंवा शेतीच्या कामासाठी उत्तम दिवस.",
    wxAdviceCloudy: "⛅ ढगाळ वातावरण — रोपांची पुनर्लागवड करण्यासाठी योग्य.",
    wxAdviceFoggy: "🌫️ धुक्याची स्थिती — शेतीचे काम सुरू करण्यापूर्वी दृश्यमानता सुधारण्याची वाट पहा.",
    wxAdviceDefault: "🌾 आज शेतीचे काम सुरू करण्यापूर्वी परिस्थिती तपासा.",
  },
}

const useLanguageStore = create((set) => ({
  language: 'en',
  setLanguage: (lang) => set({ language: lang }),
  t: (key) => {
    const lang = useLanguageStore.getState().language
    return translations[lang]?.[key] || translations['en'][key] || key
  }
}))

export default useLanguageStore
